### ISSUE TITLE
Unable to make it works

### ISSUE THREAD

**Issue by Loyz07** [asilvas/blobby-gcp-storage#1]
Hello asilvas,

First thanks for your job on image-steam it works very well with S3 ;-).

I try to use blobby-gcp-storage with image-steam but it seams i missed something.

I use the config file below for image-steam and my gcp credentials is the GOOGLE_APPLICATION_CREDENTIALS env vars:

```js
module.exports = {
  http: {
    host: '0.0.0.0',
    port: 3000,
  },
  storage: {
    defaults: {
      driverPath: 'blobby-gcp-storage',
      project: 'modulopay',
      endpoint: 'https://storage.googleapis.com',
      bucket: 'staging.modulopay.appspot.com',
    },
  },
};
```
but i get the error :

```bash
Server running at http://0.0.0.0:3000

/Users/lguegu50/Projects/modulopay/services/image-server/node_modules/@google-cloud/storage/src/file.js:110
    value: name.replace(/^\/+/, ''), // Remove leading slashes.
                ^

TypeError: name.replace is not a function
    at new File (/Users/lguegu50/Projects/modulopay/services/image-server/node_modules/@google-cloud/storage/src/file.js:110:17)
    at Bucket.file (/Users/lguegu50/Projects/modulopay/services/image-server/node_modules/@google-cloud/storage/src/bucket.js:1062:10)
    at BlobbyGCPStorage.fetch (/Users/lguegu50/Projects/modulopay/services/image-server/node_modules/blobby-gcp-storage/lib/index.js:102:30)
    at Storage.p.fetch (/Users/lguegu50/Projects/modulopay/services/image-server/node_modules/image-steam/lib/storage/index.js:83:21)
    at /Users/lguegu50/Projects/modulopay/services/image-server/node_modules/image-steam/lib/http/connect.js:184:22
    at /Users/lguegu50/Projects/modulopay/services/image-server/node_modules/async/dist/async.js:4184:13
    at /Users/lguegu50/Projects/modulopay/services/image-server/node_modules/async/dist/async.js:59:23
    at runTask (/Users/lguegu50/Projects/modulopay/services/image-server/node_modules/async/dist/async.js:932:17)
    at /Users/lguegu50/Projects/modulopay/services/image-server/node_modules/async/dist/async.js:870:35
    at processQueue (/Users/lguegu50/Projects/modulopay/services/image-server/node_modules/async/dist/async.js:880:17)
```
I know that this package is pretty old but i didn't managed to get a newer to work with gcp.

Can you help ?

Thanks.

**Comment by asilvas** [comment]
Hey @Loyz07 ! I no longer have a GCP account but happy to take a PR if there is a code problem. Looks like the problem has to do with the `fileKey` passed to this line: https://github.com/asilvas/blobby-gcp-storage/blob/master/src/index.js#L73

**Comment by Loyz07** [comment]
Hello Aaron,
I'm afraid that i've not the skills to make a PR.
Sorry about that.

**Comment by Loyz07** [comment]
Hello Aaron,

The issue was an inversion of the parameters fileKey and opts on the line "value: function fetch(opts, fileKey, cb)".

But it still doesn't work a few line later with the issue:

`/Users/.../Projects/boostizy/services/image-server/node_modules/once/once.js:25
    return f.value = fn.apply(this, arguments)
                        ^

TypeError: fn.apply is not a function
    at f (/Users/.../Projects/boostizy/services/image-server/node_modules/once/once.js:25:25)
    at f (/Users/.../Projects/boostizy/services/image-server/node_modules/once/once.js:25:25)
    at DestroyableTransform.<anonymous> (/Users/.../Projects/boostizy/services/image-server/node_modules/blobby-gcp-storage/lib/index.js:127:9)
    at DestroyableTransform.emit (events.js:387:35)
    at endReadableNT (/Users/.../Projects/boostizy/services/image-server/node_modules/readable-stream/lib/_stream_readable.js:1010:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)`

I'd really like to use your lib that correspond exactly to my needs but i don't manage too for the moment.

Hope you can help.

**Comment by asilvas** [comment]
I don't have your environment or code to reproduce, so you'll need to troubleshoot from your end.
